// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfWsCpd2AfubAUv39Myx0GwhOKHC8_4k',
    appId: '1:193551739453:web:60e1b01965bd21d2589854',
    messagingSenderId: '193551739453',
    projectId: 'flutter-mobidit-m1-iot',
    authDomain: 'flutter-mobidit-m1-iot.firebaseapp.com',
    storageBucket: 'flutter-mobidit-m1-iot.appspot.com',
    measurementId: 'G-F5QR3Y5FMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2lpNGel8VgbZqYefVP7X1FBavHNnCdMQ',
    appId: '1:193551739453:android:065be07a48d6902d589854',
    messagingSenderId: '193551739453',
    projectId: 'flutter-mobidit-m1-iot',
    storageBucket: 'flutter-mobidit-m1-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkL_f7JYgaXEHKoPTyX0pv8IznKyfAZNg',
    appId: '1:193551739453:ios:705168777324f410589854',
    messagingSenderId: '193551739453',
    projectId: 'flutter-mobidit-m1-iot',
    storageBucket: 'flutter-mobidit-m1-iot.appspot.com',
    iosClientId: '193551739453-f5nqclf2u3jj9e5ov8sgitj7ktk0c38r.apps.googleusercontent.com',
    iosBundleId: 'com.fluttermobiditm1iot.flutterMobiditM1Iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkL_f7JYgaXEHKoPTyX0pv8IznKyfAZNg',
    appId: '1:193551739453:ios:dea77a2528a59ca7589854',
    messagingSenderId: '193551739453',
    projectId: 'flutter-mobidit-m1-iot',
    storageBucket: 'flutter-mobidit-m1-iot.appspot.com',
    iosClientId: '193551739453-s9so9ivev9tfptggf05fa5f5lpei9dnj.apps.googleusercontent.com',
    iosBundleId: 'com.fluttermobiditm1iot.flutterMobiditM1Iot.RunnerTests',
  );
}
